---
title: "Victor's File"
author: "Victor M. Uribe"
date: "2022-02-25"
output: pdf_document
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```






```{r}
library(tidyverse)
library(tidymodels)
```





# feature Selection

```{r}
lasso_spec <- linear_reg(penalty = tune(), mixture = 1) %>% 
  set_engine("glmnet") %>% 
  set_mode("regression")


lasso_rec <- recipe(attendance ~., gamelog_train) %>% 
  step_normalize(all_numeric_predictors()) %>% 
  step_other(all_nominal_predictors(), threshold = .05) %>% 
  step_dummy(all_nominal_predictors())

lasso_wf <- workflow() %>% 
  add_model(lasso_spec) %>% 
  add_recipe(lasso_rec)
```





```{r}
doParallel::registerDoParallel()
set.seed(123)

lambda_grid <- grid_regular(
  penalty(),
  levels = 20
)
lasso_tune <- tune_grid(
  lasso_wf,
  resamples = gamelog_fold,
  grid = lambda_grid
)
```


```{r}
lasso_tune %>% autoplot()
```



```{r}
best_lambda <- lasso_tune %>% 
  select_best("roc_auc")
fin_lass_wf <- finalize_workflow(
  lasso_wf,
  best_lambda
)
fit_lass <- fin_lass_wf %>% 
  fit(gamelog_train)
fit_lass %>% 
  tidy() %>% 
  filter(estimate != 0)
```


